added testwise the md5 implementation. It looks quite good, but there is a problem with the flow space: md5 unfortuantely uses copy.deepcopy, which makes the flow space dig into that, and we crash with the message
AssertionError: Not generating the same operation sequence:
v4162 = simple_call((type type), v4157)
  ---> | while repeating we see here
       | v4163 = simple_call((builtin_function_or_method get), v4162)
v4163 = simple_call((builtin_function_or_method get), v4162)
v4164 = is_true(v4163)
>>>

I guess there is so much stuff in the copy module that the flow space
gets confused somehow. But well, it may be a real bug.

For now, I'll replace the copy.deepcopy part of md5 with something else,
to protect the analysis.

--HG--
extra : convert_revision : svn%3A5fdb0b31-00ae-4507-bd76-94d651a7451c/pypy/trunk/src%407657