simplified tests because PBC work now last test fails still (probably) because rpython/module/ll_os.py/ll_os_read raises an exception. (errormessage: AttributeError: 'FuncNode' object has no attribute 'write_exceptblock')
--HG--
extra : convert_revision : svn%3A5fdb0b31-00ae-4507-bd76-94d651a7451c/pypy/dist%4014836