issue 13 : testing
The test_tarfile passes on CPython, because it relies on base conversion of strings to ints ignoring null characters ie.

Python 2.4.2 (#1, Apr 24 2006, 10:25:58)
[GCC 4.0.0 20041026 (Apple Computer, Inc. build 4061)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> int('123\x00',10)
123

This behaviour is only if use base conversion ie.

>>> int('123\x00')
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
ValueError: null byte in argument for int()

Rather than changing PyPy's behaviour I have patched tarfile.py, to replace int and long with functions truncating the inputstrings on null characters

--HG--
extra : convert_revision : svn%3A5fdb0b31-00ae-4507-bd76-94d651a7451c/pypy/dist%4026557