The generated exceptions with the changes from the last check-in. It sometimes makes py.py, run on top of 2.4.1, crash on exit with:
pypy.interpreter.error.OperationError: [<W_TypeObject(TypeError)>: <UserW_Object
Object() instance of <W_TypeObject(TypeError)>>]

--HG--
extra : convert_revision : svn%3A5fdb0b31-00ae-4507-bd76-94d651a7451c/pypy/dist%4013716