objects of incompatible types are now unordeable in python3. Completely change the meaning of this test: instead of checking the ordering, we check that we always raise TypeError. Passes with -A, still fails on pypy
--HG--
branch : py3k